version: '3'
services:
  chordslasher:
    build: .
    volumes:
      - .:/chordslasher
    ports:
      - 3000:3000
    links:
      - 'db'

  db:
    image: mysql
    environment:
      MYSQL_DB: 'chordslasher_db'
      MYSQL_USER: 'starbuck'
      MYSQL_PASSWORD: 'moby_dick'
      MYSQL_ROOT_PASSWORD: 'moby_dick'
    ports:
      - 33060:33060


